/*==================================================================

            pkgswchs.h

   GENERATED by addfeatures.ndf

==================================================================*/

#define REGEXP
#define SOCKETS
#define SPROCESS
#define NTABLES
#define MEMSPACES
#define NCOMPLEX
#define NFILES
#define NDYNLOAD
